function display = drawInstructions(display, phasis)

% Define instructions
if phasis == 1
    Instructions = {'Vous allez voir un cercle dans lequel des points vont se déplacer. Soyez y très', ...
                    'attentif car il vous sera par la suite demande de juger de la direction du mouvement', ...
                    'des points en question. Attention, tous les points ne bougent pas dans la même', ...
                    'direction : certains bougent de façon totalement aléatoire ! Vous devez donc essayez', ...
                    'de deviner la direction globale du mouvement des points. Certains essais seront très', ...
                    'faciles tandis que dans d''autres il sera, au contraire, plus difficile de percevoir', ...
                    'le mouvement des points. Vous devrez donc rapporter la direction du mouvement que vous', ...
                    'avez perçu (à l''aide des touches "Flèche droite" et "Flèche gauche", validez votre', ...
                    'réponse avec la "Barre d''espace". Les points que vous gagnerez seront indexés sur', ...
                    'vos performances.'};
elseif phasis == 2
    Instructions = {'Vous allez maintenant voir des jeux de points similaires aux précédents, toutefois, certains d''entre', ...
                    'eux seront suivis d''un second jeu de points ayant exactement la même direction, mais avec une plus', ...
                    'grande cohérence. Ainsi, 2 jeux de points seront parfois présentés avant qu''il ne vous soit demandé', ...
                    'de juger de leur direction. Dans ce cas, la direction est la même ! Ainsi le second jeu devrait vous', ...
                    'aider à prendre votre décision. À chaque fois que la direction des points changent, vous en serez averti', ...
                    'par l''indication "Nouveau stimulus". Après 1 ou 2 jeux de points (ce qui varie au cours de l''expérience)', ...
                    'il vous sera donc toujours demandé de juger de l''orientation des points en question et de donner, en', ...
                    'plus cette fois, votre confiance dans votre décision (à l''aide des touches "Flèche droite" et "Flèche', ...
                    'gauche", validez votre réponse avec la "Barre d''espace"). De la même façon que précédemment, les points', ...
                    'que vous gagnerez seront indexés sur vos performances. Attention cependant, à chaque essai, si la confiance', ...
                    'que vous donnez ne reflète pas vos performances cela retirera des points de votre compteur.'};
elseif phasis == 3
    Instructions = {'Lors de cette dernière phase, après chaque présentation d''un seul et unique jeu de points,' ...
                    'vous devrez choisir si vous souhaitez répondre maintenant (vous pensez avoir clairement perçu' ...
                    'la direction des points) ou si vous préférez revoir les mêmes points avec une certaine augmentation' ...
                    'de la facilité (c''est à dire de la cohérence globale du mouvement) de 0% (même jeu de points),' ...
                    'de 5%, de 10% ou de 15% avant de prendre votre décision. Après cela, vous serez interrogé, comme' ...
                    'précédemment, sur la direction des points puis sur la confiance que vous avez dans cette décision.' ...
                    'Les points que vous gagnerez sont fonction de vos bonnes réponses et de votre choix de revoir ou non' ...
                    '(avec un certain niveau d''augmentation de facilité) un jeu de point. Comme précédemment, à chaque' ...
                    'essai, si la confiance que vous donnez ne reflètepas vos performances cela retirera des points', ...
                    'de votre compteur.'};
end

% Draw instructions
for i = 1:1:length(Instructions)
   drawText_MxM(display, [0, (-i*(display.scale/20))+(display.scale/4)], Instructions{i}, [255, 255, 255], (display.scale*2));
end

% Draw paratext
drawText_MxM(display, [0, (display.scale/(4/3))], 'Consignes', [255, 255, 255], (display.scale*4));
drawText_MxM(display, [0, -(display.scale/(4/3))], '(Appuyez sur n''importe quelle touche pour commencer)', [255, 255, 255], (display.scale*2));

% Flip it
Screen('Flip',display.windowPtr);

end